### ISSUE TITLE
channel(server.channels) is always empty

### ISSUE THREAD

**Issue by Ultracoolguy** [jesopo/ircstates#3]
So I'm writing a matchmaking-bot that, on the user's request, reads a file and pings the people inside it. However, I need to check whether the user being read in the file is connected in the channel, otherwise printing them is pointless spam. I tried doing this:

        elif line.command == "001":
            _send(irctokens.build("JOIN", [chan]))
            channel = server.channels

And this: 

        elif "PRIVMSG" in line.format() and chan in line.format():
            if ".matchmake" in line.format():
                file = open("playerlist.txt")
                content = file.read()
                ping = ""

                for line2 in content.split("\n"):
                    if line2 in channel.users:
                        ping += f"{line2} "

                _send(irctokens.build("PRIVMSG",  [chan, f"Pinging users: {ping}"]))
                file.close()

However, Python returns:

```
Traceback (most recent call last):
  File "./bot.py", line 57, in <module>
    if line2 in channel.users:
AttributeError: 'dict' object has no attribute 'users'
```

And if I print channel:
   `  {}`

I'll gladly provide any other information needed.

**Comment by jesopo** [comment]
what's the point of `channel = server.channels` in the `"001"` handler

**Comment by Ultracoolguy** [comment]
Actually I don't have a particular reason. Although I did try moving it to the start of the `while True` loop and it had the same effect.

**Comment by jesopo** [comment]
no I mean, what are you trying to achieve? `server.channels` is a dictionary of `{"#channel": Channel()}` and it will have no entries by the time we receive `001`.

in your `PRIVMSG` handler you can do `channel = self.channels[self.casefold(line.params[0])]` - `line.params[0]` will be the current channel name and `self.casefold( )` will turn it in to a lowercase name

**Comment by Ultracoolguy** [comment]
Also, do you prefer if I send the entire script?

**Comment by Ultracoolguy** [comment]
@jesopo I want to look for the people in a specific room.

**Comment by jesopo** [comment]
so remove the channel part of your `001` handler and change your `PRIVMSG` handler to look something like this:

```
    elif "PRIVMSG" in line.format() and chan in line.format():
        if ".matchmake" in line.format():
            file = open("playerlist.txt")
            content = file.read()
            ping = ""
            channel = self.channels[self.casefold(line.params[0])]

            for line2 in content.split("\n"):
                if line2 in channel.users:
                    ping += f"{line2} "

            _send(irctokens.build("PRIVMSG",  [chan, f"Pinging users: {ping}"]))
            file.close()
````

**Comment by Ultracoolguy** [comment]
At first I tried yours, but it gave me:

```
Traceback (most recent call last):
  File "./bot.py", line 53, in <module>
    channel = self.channels[self.casefold(line.params[0])]
NameError: name 'self' is not defined
```

So instead I got inspired of yours and wrote this:

        elif "PRIVMSG" in line.format() and chan in line.format():
            if ".matchmake" in line.format():
                file = open("playerlist.txt")
                content = file.read()
                ping = ""
                channels = server.channels[line.params[0].casefold()]

                for line2 in content.split("\n"):
                    if line2 in channel.users:
                        ping += f"{line2} "

                _send(irctokens.build("PRIVMSG",  [chan, f"Pinging users: {ping}"]))
                file.close()

However:

```
Traceback (most recent call last):
  File "./bot.py", line 52, in <module>
    channels = server.channels[line.params[0].casefold()]
KeyError: '#matchmaking-test'
```

**Comment by jesopo** [comment]
the way you've done `line.params[0].casefold()` is wrong but if you're getting a `PRIVMSG` from a channel you've not yet `JOIN`ed, that sounds like a problem. can I ask what IRC network this is on? you can private message me that on freenode if you'd like

**Comment by Ultracoolguy** [comment]
In case anyone wonders, the solution was to use server.parse_tokens() (although I ended up switching to ircrobots).

Thanks @jesopo !
